export const menuList = [
    {
        "id":"techeco_2022_001",
        "name":"Home",
        "linkTo":"/",
        "public":true,
        "isActive":true
    },
    {
        "id":"techeco_2022_002",
        "name":"About us",
        "linkTo":"/techeco/about_us",
        "public":true,
        "isActive":true,
    },
    {
        "id":"techeco_2022_003",
        "name":"Services",
        "linkTo":"/tecteco/services",
        "public":true,
        "isActive":true,
    },
    {
        "id":"techeco_2022_004",
        "name":"Initiatives",
        "linkTo":"/tecteco/initiatives",
        "public":true,
        "isActive":true,
    },
    {
        "id":"techeco_2022_005",
        "name":"EPR For E-Waste",
        "linkTo":"/tecteco/epr_for_e-waste",
        "public":true,
        "isActive":true,
    },
    {
        "id":"techeco_2022_006",
        "name":"Blogs",
        "linkTo":"/tecteco/blogs",
        "public":true,
        "isActive":true,
    },
    {
        "id":"techeco_2022_007",
        "name":"Contacts",
        "linkTo":"/tecteco/contacts",
        "public":true,
        "isActive":true,
    },
    {
        "id":"techeco_2022_008",
        "name":"Take Action",
        "linkTo":"/tecteco/take_action",
        "public":true,
        "isActive":true,
    }

];